### PR TITLE
Add ability to disable API and dashboard deployments

### PR DESCRIPTION
**Pull request by alexburlton-sonocent**
Closes https://github.com/sorry-cypress/charts/issues/48

Adds a simple `enabled` value for the API and dashboard services, so those deployments can be skipped for anyone not using them.

### CODE REVIEW

**Comment by tico24** [comment]
Sorry for the delay. Could you please add to the tests so that we can be sure everything else runs ok with these things disabled?

**Comment by tico24** [comment]
I forgot to mention, the tests on main now fail... but if you look at my mongodb PR (#50), I think I've fought it into submission.

**Comment by tico24** [comment]
I'll hopefully give you enough info here for you to google the rest.

`ct install --debug --config test.yaml` - you'll need to install ct for the command to work.

Having skimmed your test, I think you're right. You also need to add 1 or more values files to the ci directory that permeate between turning stuff off and on. The ci (and the above command) runs through each of those values files and then runs the tests in test.yaml against them.

I'm sure you know, but if you omit values, then it pulls the default from the main values.yml

**Comment by alexburlton-sonocent** [comment]
> I'll hopefully give you enough info here for you to google the rest.
> 
> `ct install --debug --config test.yaml` - you'll need to install ct for the command to work.
> 
> Having skimmed your test, I think you're right. You also need to add 1 or more values files to the ci directory that permeate between turning stuff off and on. The ci (and the above command) runs through each of those values files and then runs the tests in test.yaml against them.
> 
> I'm sure you know, but if you omit values, then it pulls the default from the main values.yml

Thanks for this. I've added a new value file so we can run the tests in the case when the API and dashboard are disabled.

I've been able to lint fine by using the `ct` docker image, but am struggling to get the other command to work. I'm guessing I have to mount some `kubeconfig` somehow so it's got a cluster to talk to? What I'm trying is:

```
$ docker run -it -v $(pwd):/sorry-cypress-charts quay.io/helmpack/chart-testing:latest sh
$ cd sorry-cypress-charts
$ ct install --debug --config test.yaml
```

But it errors out because it doesn't have a cluster to talk to. I guess we can see if it passes in CI? Or any tips on how I get this to work?:

```
/sorry-cypress-charts # ct install --debug --config test.yaml
Installing charts...
>>> helm version --short
>>> git rev-parse --is-inside-work-tree
>>> git merge-base origin/main HEAD
>>> git diff --find-renames --name-only 6e662434a12c12784786fa0d8a6d4090751f959d -- charts

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 sorry-cypress => (version: "0.1.37", path: "charts/sorry-cypress")
------------------------------------------------------------------------------------------------------------------------

>>> helm repo add minio https://helm.min.io
"minio" already exists with the same configuration, skipping
>>> helm dependency build charts/sorry-cypress
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "minio" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading minio from repo https://helm.min.io/
Deleting outdated charts
Installing chart 'sorry-cypress => (version: "0.1.37", path: "charts/sorry-cypress")'...

Installing chart with values file 'charts/sorry-cypress/ci/isolated-director-values.yaml'...

Creating namespace 'sorry-cypress-mvnr8g8y8a'...
>>> kubectl create namespace sorry-cypress-mvnr8g8y8a
The connection to the server localhost:8080 was refused - did you specify the right host or port?
========================================================================================================================
........................................................................................................................
==> Events of namespace sorry-cypress-mvnr8g8y8a
........................................................................................................................
>>> kubectl get events --output wide --namespace sorry-cypress-mvnr8g8y8a
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Error printing details: Error waiting for process: exit status 1
>>> kubectl get pods --no-headers --namespace sorry-cypress-mvnr8g8y8a --selector  --output jsonpath={.items[*].metadata.name}
Error printing logs: Error running process: exit status 1
Deleting release 'sorry-cypress-mvnr8g8y8a'...
>>> helm uninstall sorry-cypress-mvnr8g8y8a --namespace sorry-cypress-mvnr8g8y8a --timeout 600s
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
Error deleting Helm release: Error waiting for process: exit status 1
Deleting namespace 'sorry-cypress-mvnr8g8y8a'...
>>> kubectl delete namespace sorry-cypress-mvnr8g8y8a --timeout 180s
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Namespace 'sorry-cypress-mvnr8g8y8a' did not terminate after 180s.
>>> kubectl get namespace sorry-cypress-mvnr8g8y8a
Namespace 'sorry-cypress-mvnr8g8y8a' terminated.
------------------------------------------------------------------------------------------------------------------------
 ✖︎ sorry-cypress => (version: "0.1.37", path: "charts/sorry-cypress") > Error waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------
Error: Error installing charts: Error processing charts
Error installing charts: Error processing charts
```

**Comment by tico24** [comment]
I used k3d locally (the ci uses KinD) which handles the "deploy somewhere" issue.

That said, a couple of things it might be:
1. The chart.lock file - you might get away with just deleting it and this may stop that error
2. If you have helm installed locally you might want to remove minio and then run the tests again

If it's not those specific things, then I'm out of ideas. If you're still stuck... push what you have to this branch and we'll get the CI to do the grunt work and you can play whack-a-mole with the errors as they appear!

**Comment by alexburlton-sonocent** [comment]
> I used k3d locally (the ci uses KinD) which handles the "deploy somewhere" issue.
> 
> That said, a couple of things it might be:
> 
>     1. The chart.lock file - you might get away with just deleting it and this may stop that error
> 
>     2. If you have helm installed locally you might want to remove minio and then run the tests again
> 
> 
> If it's not those specific things, then I'm out of ideas. If you're still stuck... push what you have to this branch and we'll get the CI to do the grunt work and you can play whack-a-mole with the errors as they appear!

Changes are pushed so feel free to give CI a go! Should I duplicate the changes you made to the runner (tweaking the action version etc) first?

**Comment by tico24** [comment]
Let's find out and see what happens!

**Comment by alexburlton-sonocent** [comment]
> Let's find out and see what happens!

Looks like my new values file installs fine, but then the install of `charts/sorry-cypress/ci/latest-image-values.yaml` fails? Does this look like the error you were fighting with on your branch?

**Comment by tim-sendible** [comment]
If you modify your values.yaml to turn mongodb on by default, this should fix the issue... if it doesn't, then it'll be a cherrypick between yours and mine and maybe I'll just submit a patch to master to fix the tests in the first place!

Turns out mongodb should always be on... previously it didn't have to be.

**Comment by tim-sendible** [comment]
And now I'm commenting with the wrong account :)

**Comment by alexburlton-sonocent** [comment]
Ok thanks, I've pushed up that change (and updated the README accordingly :grin: )

**Comment by alexburlton-sonocent** [comment]
Hmm, same failure - API service sad because it can't talk to mongo. I've double-checked and `charts/sorry-cypress/ci/latest-image-values.yaml` doesn't override `mongo.enabled` in any way, so not sure why this would still be broken now it's enabled by default? Any ideas? :thinking:

**Comment by tico24** [comment]
Ah yeh - there's other changes needed. If/when I get time, I'll fix the tests on master and maybe this'll just pass then.

**Comment by tico24** [comment]
The CI on `main` is now fixed, so in theory if you do the merging dance your tests will now pass.... probably.

**Comment by tico24** [comment]
Can you also please set your chart version to `1.0.0-alpha1`, and note that the appversion has changed (although you should find that in the merge)

**Comment by alexburlton-sonocent** [comment]
> The CI on `main` is now fixed, so in theory if you do the merging dance your tests will now pass.... probably.

Yaaas, :heavy_check_mark:

**Comment by tico24** [comment]
Can you also please set your chart version to `1.0.0-alpha1` ? And then I think it's good to go.

**Comment by tico24** [comment]
Thanks so much for your patience with the CI, and contribution of course!

**Pull request merged**
