### PR TITLE
Use Bitnami Minio Chart

### LINKED ISSUE #45: Minio Helm chart is deprecated in favour of an operator
We will have to follow suit at some point.

https://github.com/minio/charts/tree/master/minio

### PR DESCRIPTION
**Pull request by keyute**
Fixes #45. There might be some values I've missed in the template as its only edited enough to fit my current deployment.

### CODE REVIEW

**Comment by tico24** [comment]
Please can you update the changelog and the chart version? Thanks.

**Comment by tico24** [comment]
I could be wrong, but this looks like a breaking change to me. Presumably any data in existing minio will disappear.

So this should be a large version number increase, and appropriate shoutyness in the changelog.

**Comment by keyute** [comment]
I'm not sure how migrating from the old minio chart to the new chart will look like as I've deployed it as a new installation. Perhaps someone with an older existing installation can help out here.

**Comment by tico24** [comment]
Hi there. I'll close off this PR in a few weeks because it has sat dormant for some time.

**Pull request closed without merging**
