### PR TITLE
feat: Add MINIO_READ_URL_PREFIX env

### PR DESCRIPTION
**Pull request by baczus**

### CODE REVIEW

**Comment by tico24** [comment]
I'm unsure what problem this is solving? People can add additional minio chart values themselves. Is it now a mandatory field?

If so, we also need the chart version updated, and the changelog.

**Comment by baczus** [comment]
`MINIO_READ_URL_PREFIX` helps configure `browser` <-> `minio` <-> `director` communication and it can be set in `director` component.

 I'm not sure how can I pass this property to `director` without this MR

Docs: https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration.

**Comment by tico24** [comment]
ah yup, that's fair. I didn't spot that. 

Cool. If you can update the chart version and add the changelog, we can push this through. You'll need to merge in main too because I pushed an update a few mins ago.

**Comment by baczus** [comment]
Updated

**Pull request merged**
