### PR TITLE
feat: allow setting record keys from existing Kubernetes secret

### PR DESCRIPTION
**Pull request by aridelsante**
Thank you for offering a contribution to the Sorry Cypress Helm charts.

In order to ensure some level of quality, there are a few hoops to jump through. Please do not create a Pull Request until you have performed all these steps:

Checklist:

* [x] I have increased [the chart version](https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/Chart.yaml#L5).
* [x] I have updated the [chart readme](https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/README.md) to reflect mny change.
* [x] I have updated the [chart changelog](https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/changelog.md) to reflect my change.
* [ ] I have updated/added any [CI tests](https://github.com/sorry-cypress/charts/tree/main/charts/sorry-cypress/ci) to cover my change.
* [ ] I have [Run the CI locally](https://github.com/sorry-cypress/charts/tree/main/charts/sorry-cypress/contributing/README.md).

### CODE REVIEW

**Comment by fbritoferreira** [comment]
@aridelsante looks like your change is failing on CI could you take at look at fixing the tests?

**Comment by aridelsante** [comment]
> @aridelsante looks like your change is failing on CI could you take at look at fixing the tests?

@fbritoferreira I've run those exact checks from my fork (disabling fail-fast for convenience) and they [are successful](https://github.com/aridelsante/charts/actions/runs/4123433526/jobs/7121664186) after retrying some of them.

 Have you perhaps also noticed those tests being flaky overall?

**Comment by fbritoferreira** [comment]
@aridelsante I notice this on my own branch, I will try and get some time today to fix it

**Comment by fbritoferreira** [comment]
@aridelsante If you go ahead and fix the conflicts I will merge it once its done

**Comment by aridelsante** [comment]
Apologies for the delay @fbritoferreira, the conflicts are now resolved! Thank you!

**Comment by apeduru-patreon** [comment]
Can this be merged in yet? Would love to start using this as opposed to writing out the record keys in cleartext.

**Pull request merged**
