### PR TITLE
Update Chart.yaml

### PR DESCRIPTION
**Pull request by alessioerosferri**

### CODE REVIEW

**Comment by fsmaia** [comment]
Hey guys, do you think we should go to v1 before the first stable version? IMHO it could.

BTW, what is this `appVersion` purpose, since the API/dashboard/director allows setting the image tag?

**Comment by tico24** [comment]
appVersion is the default. By default we don't set the image tag in values.yml

I think we should go to v1 when sorry-cypress goes stable and we switch to the mongodb helm installation (which I'm struggling for time to do) - so I disagree with this PR.

**Review by tico24 — COMMENTED** [review]
We should be tracking stable. RCs aren't stable.

**Comment by fsmaia** [comment]
Agreed!

**Pull request closed without merging**
