### PR TITLE
change driver checking to minio driver

### PR DESCRIPTION
**Pull request by osiastedian**

### CODE REVIEW

**Comment by osiastedian** [comment]
Just wondering why is there a discrepancy between the docker-compose version.

https://github.com/sorry-cypress/sorry-cypress/blob/master/docker-compose.minio.yml

**Review by fsmaia — APPROVED** [review]

**Comment by fsmaia** [comment]
Hey, thanks for the contribution!

The discrepancy between docker-compose version and this was because the initial use case didn't include MinIO, but feel free to adjust this.

Could you update the S3/MinIO section on the chart to specify that MinIO has its own `screenshotsDriver`?

**Comment by osiastedian** [comment]
@fsmaia I've updated the readme. I hope the change is enough. :D

**Comment by osiastedian** [comment]
@agoldis  @tico24  I'd like to follow up for a review. 😄

**Pull request merged**
